### ISSUE TITLE
How the mesh model is rendered.

### ISSUE THREAD

**Issue by jieeeeeeeeeee** [zju3dv/NeuralRecon-W#2]
This is an excellent study, and the results in your paper look stunning. Your mesh model can easily show the details. I don't get that effect when I open a mesh model using meshlab. I would like to know what method or tool you use to render the mesh models. Thank you very much.

**Comment by JiamingSuen** [comment]
Thanks for your interest in our work! The color is the Ambient Occlusion baked into mesh vertex colors. This is done through MeshLab.
<img width="948" alt="image" src="https://user-images.githubusercontent.com/8616975/170829106-c235b377-80c6-4f2d-8254-31f9954d4ef4.png">

**Comment by jieeeeeeeeeee** [comment]
I'm so stupid that this function is in meshlab🤣. Thank you for your guidance 👍👍.

**Comment by HaFred** [comment]
Hi all, I have just a follow-up question. With _Ambient Occlusion_ in MeshLab, I can only get the left-hand side color result. How about the right-hand side? Thank you.
![image](https://user-images.githubusercontent.com/13991298/170850107-60152e51-fac2-4f91-bb01-843c124e86ba.png)

**Comment by JiamingSuen** [comment]
This demo is rendered in Blender, where you can output surface normals in render layers. In MeshLab, you may use this shader to show surface normal.
[meshlab-normal-shader.zip](https://github.com/zju3dv/NeuralRecon-W/files/8793589/meshlab-normal-shader.zip)
