### ISSUE TITLE
reproduce ablation studies of different sampling strategy

### ISSUE THREAD

**Issue by LongruiDong** [zju3dv/NeuralRecon-W#24]
Hi~

Thanks for openning source this great work!

I am quite interested in the experiment showed at Fig 6 in your paper---comparision about different sampling strategies.
Can the current version of the code be easily switched between different sampling methods, so that this experiment can be reproduced?

Thanks in advance!

**Comment by Burningdust21** [comment]
Hi, to use voxel-guided sampling, you can change options `NEUCONW.UPDATE_FREQ`  and `NEUCONW.S_VAL_BASE` in [training config](https://github.com/zju3dv/NeuralRecon-W/blob/main/config/train.yaml#:~:text=TRAIN_VOXEL_SIZE%3A%200.04-,UPDATE_FREQ%3A%205000,-N_VOCAB%3A%205000) to be 0, and increase the number of samples and up-sample steps. 

To use sphere-guided sampling, you need to change [this](https://github.com/zju3dv/NeuralRecon-W/blob/main/datasets/phototourism.py#:~:text=%3DTrue%2C-,use_voxel%3DTrue%2C,-scene_origin%3DNone) to `False` and regenerate caches, then increase samples as described above.
