### ISSUE TITLE
Input ROI

### ISSUE THREAD

**Issue by Sapium59** [zju3dv/NeuralRecon-W#28]
It may sound stupid that I have no idea how to set ROI well for input.
For now, I take some photographs and then run COLMAP. COLMAP outputs a mesh computed through Delaunay triangulation. By visualizing I find this mesh is skewed (3d-rotated from a real world coordinate system) and drifted (3d-translated).
What I do now is 1. ignore rotation because I dont know how to deal with, 2. manually set in dataset config the center and radius and bbx and bbx_detail so they cover my region of interest. I noticed other issue mentioned center and radius from neus, but I am not familiar with that and hope for a direct method tk determine these params.
I believe there are better solutions. Would you like show me?

I can run through the pipeline and get some result, but these meshes seem to cover more space than my ROI bbx. I think something must be configured incorrectly. Can you show me how to config everything important for training a scene?

**Comment by Burningdust21** [comment]
Hi, you should use the manual selection preprocessing pipeline, set RoI in bbx option in `config.yaml` , and set the origin as well as radius according to your bbx.
