### ISSUE TITLE
About detailed comparison to NeuS

### ISSUE THREAD

**Issue by MiZhenxing** [zju3dv/NeuralRecon-W#3]
Hi, many thanks for your excellent work and can wait to read your codes!
I have a question about the experiments in the paper. In the experiments, the compared nerf-like method is only NeRF-W. NeuS is not used for detailed comparison in Table 1 and Figure 7. In my opinion, NeRF-W is not directly proposed for surface reconstruction. If we extract the surface from NeRF-W, we need to set a threshold for the density, which may vary in different locations and scenes. This drawback will make it hard to extract a reasonable surface from NeRF-W. However, NeuS is directly for surface reconstruction because it estimates SDF. It shows very good results in tiny scenes. I think your pipeline is also based on NeuS. So could you provide more detailed comparison results with respect to NeuS? It would provide more evidence of your main contribution of the sampling strategy. Thank you!

**Comment by JiamingSuen** [comment]
Please refer to the "sphere-based" baseline in ablation studies.
