### ISSUE TITLE
How to make my own datasets?

### ISSUE THREAD

**Issue by lulianLiu** [zju3dv/NeuralRecon-W#38]
Dear author,thanks you great work. I have some buildings images, I want to use them to train to reconstruction?how can I to make my own  datasets?

**Comment by rockywind** [comment]
+1

**Comment by Burningdust21** [comment]
Hi, you should run CPLMAP sparse reconstruction on your own datasets, instructions on COLMAP can be found [here](https://colmap.github.io/cli.html). We provide an automatic scripts in readme  that takes a CPLMAP workspace and convert to our data format.
