### ISSUE TITLE
How do you get a textured/colored 3D model?

### ISSUE THREAD

**Issue by BarnitaSharma** [zju3dv/NeuralRecon-W#39]
Since this model is built on top of NeUS, it should have both 3d geometry and appearance reconstructed. How do we obtain the textured model from the code?

**Comment by Burningdust21** [comment]
Hi, the provided scripts for extracting mesh outputs vertex color by default.

**Comment by BarnitaSharma** [comment]
Then, why does it output a grayscale 3D model? Also, in the reconstruction showcase (https://zju3dv.github.io/neuralrecon-w/), colored models are not displayed. Please let me know the modifications required to get an RGB model.  I had trained it but even though the script apparently shows to be generating vertex colors, the extracted mesh is colorless.
