### ISSUE TITLE
How to calculate AUC P/R/F1?

### ISSUE THREAD

**Issue by Dawars** [zju3dv/NeuralRecon-W#45]
I'm trying to compare the results in the paper with my own but I get wildly different results for AUC values.

I'm using 

```python
from sklearn import metrics

metrics_json = json.loads((pred_dir/"eval_bg_reprojected.ply"/"metrics.json").read_text())
auc_precs = sklearn.metrics.auc(metrics_json["thresholds"], metrics_json["precs"])
```

For comparable precision values I get very different AUC precision values (BG scene):

28.6 vs 86.25 (mine)

**Comment by Burningdust21** [comment]
Hi, we define the AUC of the F1 score as the area under the curve of the F1-threshold plot, not the P-R curve in sklearn. The same holds for the AUC of Precision and Recall. Details can be found in [supplementary material](https://zju3dv.github.io/neuralrecon-w/files/neuconw-supp.pdf)
