### ISSUE TITLE
The details of Surface-guided sampling

### ISSUE THREAD

**Issue by Huang-ZhangJin** [zju3dv/NeuralRecon-W#5]
Thanks for posting such excellent work!

I try to understand the **Surface-guided sampling** part of your paper, however, I'm confused about how to get the queried surface position  $\hat{x}$, and how to sample within the interval $(\hat{x}-t_s, \hat{x}+t_s)$. 
- Is $\hat{x}$ indicates the point where the ray intersects the surface? If so, how to query $\hat{x}$?
- Is the queried points within interval $(\hat{x}-t_s, \hat{x}+t_s)$ a uniform distribution or Gaussian distribution or any others?

Also, looking forward to your code release！

**Comment by ThePrecoder** [comment]
Bro,I have the same question haha~Both of the question that what is the true meaning of " sampling only within a sparse
voxel volume around surfaces estimated from SfM point clouds".I get what the author want to do ,but I just dont know how to Replicate such operations.

**Comment by JiamingSuen** [comment]
We use a uniform distribution for surface-guided sampling, please refer to the corresponding [code](https://github.com/zju3dv/NeuralRecon-W/blob/a9c08b0175e53719e6bc7db718b7f9d3b79051d0/rendering/renderer.py#L489) for more details.
